### ISSUE TITLE
what can i do?

### ISSUE THREAD

**Issue by jansonjoan** [OkBuilds/OkBuck#66]
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(cn.smssdk.b.c) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

**Comment by Piasy** [comment]
I think this is the issue of BUCK, please open an issue in BUCK repo.

**Comment by kageiit** [comment]
This is not unique to buck. This is just caused by dx tool from android. This will show up even in gradle. Its just a warning message you can safely ignore.

Yo get it to go away, you need to get the sdk authors of the library (cn.smssdk.b.c) you are using to recompile their library using latest javac compiler. They probably might be using jdk 1.6.

This is quite a common problem among sdks from chinese vendors like baidu etc. from the package name of the class, it seems this sdk is also from some chinese sdk vendor.

**Comment by jansonjoan** [comment]
Thank you
